apiVersion: v1
kind: ConfigMap
metadata:
  name: atlantis-demo-config
  labels:
    app: atlantis-demo
data:
  repo-allowlist: "github.com/*"
  repo-config.json: |
    {
      "repos": [
        {
          "id": "/.*/",
          "allowed_overrides": ["workflow"],
          "apply_requirements": ["approved"]
        }
      ],
      "workflows": {
        "default": {
          "plan": {
            "steps": [
              "init",
              "plan"
            ]
          },
          "apply": {
            "steps": [
              "init",
              "apply"
            ]
          }
        }
      }
    }
