apiVersion: v1
kind: Service
metadata:
  name: go-demo
  labels:
    app: go-demo
spec:
  type: ClusterIP
  selector:
    app: go-demo
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
